### ISSUE TITLE
Add a way to see the "top X articles" within given range

### ISSUE THREAD

**Issue by MusikAnimal** [MusikAnimal/pageviews#1]
The WMF-provided pageviews API has an [endpoint](https://wikimedia.org/api/rest_v1/?doc#!/Pageviews_data/get_metrics_pageviews_top_project_access_year_month_day) for this data, however it is currently not working :( This means we cannot provide this information right now, but we'll continue to monitor and implement it into the pageviews tools when it is working.

**Comment by MusikAnimal** [comment]
Update: This is in the works and I expect a working product within a week or so

**Comment by kaldari** [comment]
Have you seen http://top.hatnote.com/en/wikipedia/2016/3/9.html? Maybe we could steal some interface ideas from them. Also note that they automatically filter out Main Page, -, and possibly some other stuff.

**Comment by MusikAnimal** [comment]
@kaldari Nice! I wonder how they are filtering out the false-positives. I'm guessing it's done manually. I do like the images, we could fetch that from Wikidata pretty easily. Some data like the "streak" isn't feasible for us to compute, I think

**Comment by MusikAnimal** [comment]
Working product at https://tools.wmflabs.org/topviews

Enhancements to come!

**Comment by kaldari** [comment]
Seems like it would be good idea to at least hide Main Page and Special:Search by default.

**Comment by MusikAnimal** [comment]
@kaldari Only problem is the titles are different per-project. We could add them as a i18n message, or maybe query Wikidata to get all the names and cache it somewhere.
