### ISSUE TITLE
Export CSV

### ISSUE THREAD

**Issue by abartov** [MusikAnimal/pageviews#100]
Add option to download a CSV with the data.

**Comment by MusikAnimal** [comment]
The work is done, will be deploying very soon!

**Comment by MusikAnimal** [comment]
@abartov If you meant [Langviews](http://tools.wmflabs.org/langviews) or [Massviews](http://tools.wmflabs.org/massviews), then you should be all set. You can now export as CSV or JSON.

[Topviews](http://tools.wmflabs.org/topviews) is the only app left that doesn't have an export option. This one is a bit tricky and I'll need to do other work first. Going to close this issue and open a new one for the remaining work for Topviews. Thanks
