### ISSUE TITLE
No result for zh-yue in Langviews Analysis

### ISSUE THREAD

**Issue by ktchankt** [MusikAnimal/pageviews#102]
I tried to compare some articles containing zh-yue version, but zh-yue results are always missing. 

Take https://www.wikidata.org/wiki/Q8260848 as an example, it has 3 languages:  en, zh, zh-yue. However, whatever using en, zh or zh-yue as Source project, only en and zh results are shown.

zh-yue as Source project:
https://tools.wmflabs.org/langviews/?project=zh-yue.wikipedia.org&platform=all-access&agent=user&range=latest-20&sort=views&direction=1&page=%E4%BD%95%E9%9B%81%E8%A9%A9

zh as Source project:
https://tools.wmflabs.org/langviews/?project=zh.wikipedia.org&platform=all-access&agent=user&range=latest-20&sort=views&direction=1&page=%E4%BD%95%E9%9B%81%E8%A9%A9

en as Source project:
https://tools.wmflabs.org/langviews/?project=en.wikipedia.org&platform=all-access&agent=user&range=latest-20&sort=views&direction=1&page=Stephanie_Ho

**Comment by MusikAnimal** [comment]
Interesting. I will investigate! Thanks for the report

**Comment by MusikAnimal** [comment]
Fixed with d00dc4184568a6dc8ddf0d3e05d3d3dea186cf49 ! Sorry about that! The code wasn't accounting for wikis that contain hyphens. Additionally Wikidata returns them as underscores, which must be replaced with hyphens before querying the Pageviews API.
