### ISSUE TITLE
API timeout error doesn't include page title in langviews

### ISSUE THREAD

**Issue by kaldari** [MusikAnimal/pageviews#105]
In the langviews interface, if the API times out, it gives the following error:
"Due to API failure, the following pages could not be processed: $1 Please wait several minutes and try again."
It looks like the page title isn't being passed to the i18n function for the api-error-timeout message.

**Comment by MusikAnimal** [comment]
Whoops, you'd be correct! I missed this when I went back and tried to make all the error messages more general, and not app-specific. I guess in Langviews we just need to keep track of pages that failed and list them like we do in Massviews https://github.com/MusikAnimal/pageviews/blob/master/javascripts/massviews/massviews.js#L324

**Comment by MusikAnimal** [comment]
Should be fixed! Thanks
