### ISSUE TITLE
Order of output

### ISSUE THREAD

**Issue by bluerasberry** [MusikAnimal/pageviews#108]
This is an issue with Massviews, a variation of pageviews, and for clueless end users like me. The problem is that output for Massviews is in a different order than the input list, and I wish that there were an option to get output to be given as the same order as input.

The input to massviews can be a list of articles. In the output, that list is re-ordered by default from most to least popular, but may also be sorted alphabetically. It does not seem to be an option to have the output be a list that is the same order as the input.

When I get output from this, I copy/paste it into a spreadsheet that is ordered in a certain way. I do not currently know how to match items in massview's output to automatically rearrange rows to match my records in the original list, which is what I need to do.

Thanks.

**Comment by MusikAnimal** [comment]
Got it. This shouldn't be difficult to implement, stay tuned!

**Comment by MusikAnimal** [comment]
@bluerasberry give it a go now! Thanks for the feedback :)

**Comment by MusikAnimal** [comment]
Also don't forget there is a "Export as CSV" link at the bottom!
