### ISSUE TITLE
"Massviews Analysis provides data from $3 forward."

### ISSUE THREAD

**Issue by quimgil** [MusikAnimal/pageviews#109]
In http://tools.wmflabs.org/massviews/, when clicking the "Dates" textfield, a calendar view appears. The footer shows a "$3".

> Massviews Analysis provides data from $3 forward. For older data, try stats.grok.se.

Someone might think that you are charging 3 bucks for special reports.  :)

Except for this glitch, I am impressed with this Massview tools!

**Comment by MusikAnimal** [comment]
Hehe, just forgot to pass in the date value to the i18n function. All set! Thanks for the report and your kind words :)
