### ISSUE TITLE
Pagelist views do not work for ro.wp

### ISSUE THREAD

**Issue by strainu** [MusikAnimal/pageviews#110]
Not sure if this is a bug or feature request. I tried with 

https://ro.wikipedia.org/wiki/Categorie:Monumente_din_jude%C8%9Bul_Arad (small)
and
https://ro.wikipedia.org/wiki/Categorie:Liste_de_monumente_istorice_din_Rom%C3%A2nia (much larger)

The progress bar appears, but remains at 0. The tool works for en.wp, so probably not a client issue.

**Comment by MusikAnimal** [comment]
Should be all set! Sorry about that, the API is a bit strict about encoding, I just wasn't doing it exactly right. Thanks for the report!
