### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by ANDR0BETA** [MusikAnimal/pageviews#112]
Could we have the default articles that show up in Pageview Analysis (cat and dog) change according to the language of the viewer?

Also I attached some screenshots with things that don't translate. 

![screenshot_3](https://cloud.githubusercontent.com/assets/18738179/15507788/aafd869c-21d5-11e6-8c30-61df6d6166d3.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/18738179/15507785/aaeda52e-21d5-11e6-88f8-122b43021c35.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/18738179/15507786/aaef53ba-21d5-11e6-97ea-e18c0fb590eb.png)
![screenshot_8](https://cloud.githubusercontent.com/assets/18738179/15507787/aaf58c30-21d5-11e6-80e9-6a53daeebd42.png)
![screenshot_9](https://cloud.githubusercontent.com/assets/18738179/15507790/ab0333b2-21d5-11e6-9817-35158ff8f01c.png)
![screenshot_10](https://cloud.githubusercontent.com/assets/18738179/15507789/aaffdd20-21d5-11e6-8751-4b89a3972be6.png)

**Comment by MusikAnimal** [comment]
Thanks for screenshots and annotations! I can set these messages up for i18n, no problem.

Setting the default articles for other wikis means we'd to query wikidata first, but I should be able to cache the result so it won't slow things down noticeably.

**Comment by ANDR0BETA** [comment]
Thank you also for your continued effort :)

**Comment by MusikAnimal** [comment]
Translations should be all set. Recommendation about default articles is still an open issue at #117
