### ISSUE TITLE
Don't preselect first entry (blue bar) in autocompletion list

### ISSUE THREAD

**Issue by triggernest** [MusikAnimal/pageviews#113]
Love your page view tool.  The list of suggested page names that dynamically appear as one types is very helpful.  HOWEVER, the dynamically changing **blue highlight bar** that jumps around in the list of page name suggestions is extremely distracting.  Suggest you keep the operation of the dynamically changing list exactly as it is now– but completely remove the very annoying jumping highlight.  User can simply click or press on the name he wants.

Also, it would be very helpful if the mouse focus would always go to the page field whenever it is empty.

ET Trigg

**Comment by MusikAnimal** [comment]
@triggernest First off, let me make sure you're talking about [Pageviews](http://tools.wmflabs.org/pageviews), as opposed to [Langviews](http://tools.wmflabs.org/langviews), as both have a blue highlight bar in the search, but function in a different way.

Assuming you mean Pageviews, I'm going to guess the complaint is how it says "Searching..." which pushes the blue highlight bar down one row, then it pops back up when the search is complete. Is that correct?

Please also let me know which browser and operating system you are using. E.g. Chrome on Windows 7, etc.

Auto-focusing on the search field when empty is something I can definitely do, so look forward to that being implemented.

Thanks for the feedback! :)

**Comment by triggernest** [comment]
Thank you MusikAnimal,
I am talking about Pageviews.My browser is Google Chrome Version 49.0.2623.112 (64-bit)My computer is a MacBook Air My operating system is OS X Version 10.8.5
RE: "Searching..." which pushes the blue highlight bar down one row, then it pops back up when the search is complete. Is that correct?
Yes, that's the feature that I find so very distracting.  (Anything that moves on a web page is generally annoying; that is why advertisers love to do it.)  Do you really need that blue bar?  I understand why you did it.  The blue highlighted item is the one chosen if you ask for the default by, say, hitting the Enter key - and this default keeps changing as you type.  Another way to achieve this would be to have a discreet little arrow to the left of the default item that moves down and pops up.  Another way to make it less obtrusive is to use fade-out/fade-in for bar or arrow.
But I repeat - do you really need the blue highlight?  Look at the way the Search Box in Wikipedia is implemented.  It is dynamic like yours, has no highlight, and yet functions perfectly IMHO.  Speaking of Wikipedia, what do you think of the article Wikipedia:Pageview statistics?  I can think of a few improvements.
So glad you can fix the mouse focus issue.  (Now please talk to Apple and ask them why they cannot implement "focus follows mouse" like they once did !)
IAC, kudos on a great piece of programming and a fairly decent interface.  I can only imagine how difficult it was to write.  
I was a career programmer and am an expert on interfaces.
There have only been a few perfect software product interfaces since the computer revolution of 1984.  I would include Hypercard, WriteNow, Pearl Lisp, and perhaps Excel before they ruined it.  Maybe your product will make the list.  (And who killed most of these terrific products?  Not the Evil Bill Gates–as one might expect–but the Evil Apple Inc.)
If you want any more feedback on your program's interface, just ask me.
Thank you
Ernest Trigg

**Comment by MusikAnimal** [comment]
Developer notes: We *might* be able to get Select2 to hide the blue bar (selected entry) by default, or resort to the easier solution: Remove the "Searching..." label. I'm thinking we should probably do both.

**Comment by MusikAnimal** [comment]
Fixed with dadc31d0799fc6684ccd011655a24059b692809c

I went with just removing the "Searching..." label, which WMF sites and others don't use. This will get rid of the "jumping" of the blue bar. Removing the default selection entirely is a bit tricky, as we're using a third-party library for this.

Also now if there are no entries the search field will have focus.
