### ISSUE TITLE
Restore straight line chart as opposed to bezier curve

### ISSUE THREAD

**Issue by MusikAnimal** [MusikAnimal/pageviews#116]
The curved lines, while arguably more aestheticly pleasing, imply that the data is continuous when it is not. The data we have represents daily figures, and what happens in between is unknown. Let's bring back the straight lines.

**Comment by MusikAnimal** [comment]
Done!

**Comment by ANDR0BETA** [comment]
How about making it into another chart option? :P

**Comment by MusikAnimal** [comment]
@ANDR0BETA Not a bad idea! I can add it as a "Setting", since it's still technically the same chart type
