### ISSUE TITLE
Add delimiters to totals (perhaps optional)

### ISSUE THREAD

**Issue by MusikAnimal** [MusikAnimal/pageviews#12]
When the totals get very large, it'd be helpful to delimit the numerical values. E.g. `1,234,456` instead of `123456`. This will require some i18n as other countries use different delimiters such as periods. We may want this to be optional, as people copy and paste the totals to other places (templates on wiki, etc), where the delimiters would need to be removed.

**Comment by nemobis** [comment]
Like date format, this is something that CLDR provides. Hopefully https://github.com/rxaviers/cldrjs can help, if not ask Krinkle?

**Comment by MusikAnimal** [comment]
For this I think we could use [Number.prototype.toLocaleString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString). It seems to be well-supported these days, and will go off the computer's or browser's language settings.

**Comment by MusikAnimal** [comment]
@nemobis I've deployed this change. Could you confirm everything looks okay on your end?

**Comment by nemobis** [comment]
MusikAnimal, 15/02/2016 06:22:
> Could you confirm everything looks okay on your end?

Looks good!

**Comment by MusikAnimal** [comment]
Great! Closing this issue
