### ISSUE TITLE
Option to remove display of canonical namespace names

### ISSUE THREAD

**Issue by MusikAnimal** [MusikAnimal/pageviews#14]

**Comment by kaldari** [comment]
What does this mean?

**Comment by MusikAnimal** [comment]
I think it means change `User:MusikAnimal` to `MusikAnimal`. Requested by [User:°](https://meta.wikimedia.org/wiki/User:%C2%B0) at [meta:Talk:Community Tech/Pageview stats tool](https://meta.wikimedia.org/wiki/Talk:Community_Tech/Pageview_stats_tool)

**Comment by MusikAnimal** [comment]
I don't get this and am going to close it because it seems very trivial, falling short of a "nice-to-have" in my opinion. If more people request something like this it can be revisited.
