### ISSUE TITLE
Allow fetching data earlier than 2015-10-01

### ISSUE THREAD

**Issue by nemobis** [MusikAnimal/pageviews#17]
If I manually enter an URL like https://tools.wmflabs.org/pageviews/#start=2015-09-01&end=2015-09-30&project=it.wikipedia.org&platform=all-access&agent=user&pages=Foibe_(film) I get:
> Invalid parameters! Pageviews API does not contain data older than October 2015. Sorry.

That's not true (any longer): https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/it.wikipedia/all-access/user/Foibe_(film)/daily/2015090100/2015093000 and https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/it.wikipedia/all-access/user/Foibe_(film)/daily/2015080100/2015083000 (ok, no data before 2015-08-01 yet, it seems).

**Comment by MusikAnimal** [comment]
I've explained this in the [FAQ](http://tools.wmflabs.org/pageviews/faq/) but I guess I should update that error message. I'm told we the data from August and September is spotty and shouldn't be used, for whatever reason. I saw your note on #8, when WMF does backfill the data I'll of course adjust the permitted date ranges accordingly :) Closing this for now
