### ISSUE TITLE
date representation middle endian

### ISSUE THREAD

**Issue by za-mi** [MusikAnimal/pageviews#178]
please switch to ISO 8601, this drives me nuts
https://xkcd.com/1179/

**Comment by MusikAnimal** [comment]
@za-mi The tool by default formats dates based on what is the localized format for your language, as set in your browser or computer settings. See [here](https://github.com/MusikAnimal/pageviews/blob/master/javascripts/shared/pv.js#L503-L712) for the map of languages/formats. If it is the wrong format for your language let me know.

Anyway I think it's clear you want ISO 8601, which you can force by opening the "Settings" and unchecking "Localize date format". This setting will be remembered on the same browser and computer, assuming you aren't blocking cookies.

**Comment by MusikAnimal** [comment]
@za-mi Going to close this assuming the above works for you :) Let me know if there's anything more I can do.
