### ISSUE TITLE
Option to disable autocomplete entirely

### ISSUE THREAD

**Issue by nemobis** [MusikAnimal/pageviews#18]
I can see a graph at https://tools.wmflabs.org/pageviews/#start=2015-10-01&end=2015-12-31&project=it.wikipedia.org&platform=all-access&agent=user&pages=Foibe_(film) after I constructed the URL manually, but if I try to reach the same point by typing in the interface I can't because the page no longer exists.

It would be nice to either have the validation recognise that a title is valid, but the page was deleted (perhaps by looking at whether there are items for that title in the logs?); or to allow a way to force the requested title. Altering the URL isn't so obvious, also because just hitting "enter" will not reload the graph, one has to copy the URL into a new tab.

**Comment by MusikAnimal** [comment]
This is a tricky one. The autocomplete uses the [opensearch](https://www.mediawiki.org/wiki/API:Opensearch) endpoint, which does not return deleted pages. Furthermore, the API won't necessarily retain data on them, but I could be wrong.

The issue about having to use a new tab when manually updating the URL I can probably fix, however. That's about the best I can do :/

**Comment by nemobis** [comment]
Data about deleted pages is definitely kept, the graph still works. Autocompletion for deleted titles is impossible, but maybe there is no need to reject them altogether. Your call.

**Comment by MusikAnimal** [comment]
I could add an option to remove autocomplete entirely? It is a much-needed feature, and we're already allowing it to return redirects, which I need to make a defaulted-off option. See #9

**Comment by kaldari** [comment]
I haven't been able to get data for deleted pages from the API. For example, the page Gradology was deleted today, but...
https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/en.wikipedia/all-access/user/Gradology/daily/2015111800/2016021500
... returns a 404.
Same for Jonathan_Tshibadi, James_R._Hudson, and others. So I would suggest keeping the autocomplete validation.

**Comment by MusikAnimal** [comment]
@kaldari Usually data isn't available until a day later, but I imagine the jobs that copy over the data may not run if the page has been deleted. So if a page is created and deleted on the same day, it may never make it to the pageviews API. I'm still ok with disabling autocomplete as an option, as it's fairly easy to do. I was thinking three options:
* Autocomplete
* Autocomplete and show redirects
* No autocomplete

Right now we're autocomplete w/redirects, which isn't ideal.

**Comment by MusikAnimal** [comment]
Closing as won't fix. DIsabling autocomplete entirely means we'll have to ditch the Select2 plugin and implement some other means to add pages. You'll have to manually type in the page names in the URL for now. I will however make a new issue to get around the URL hash conflict – where if you update the URL params you have to hit enter twice before the page actually reloads.

**Comment by MusikAnimal** [comment]
@nemobis I managed to pull this off. Try using the "No autocompletion" setting and you can manually enter in pages – whether they are deleted or not. Best

**Comment by nemobis** [comment]
MusikAnimal, 20/02/2016 00:23:
> @nemobis <https://github.com/nemobis> I managed to pull this off. Try
> using the "No autocompletion" setting and you can manually enter in
> pages – whether they are deleted or not. Best

Oh, thanks! I'll play with it tomorrow. I hope it didn't take too much 
time in the end, your WONTFIX'ing made sense too. :)
