### ISSUE TITLE
The string "most-viewed pages" appears to be hard-coded and untranslatable

### ISSUE THREAD

**Issue by amire80** [MusikAnimal/pageviews#183]
Under the chart there is a line saying "Ranked 173 of the most-viewed pages for March 2017".

When the site is viewed in another language, "most-viewed pages" stays untranslated.

![default](https://cloud.githubusercontent.com/assets/346271/24693517/9b5031b8-19e6-11e7-9ae1-dc796f3e0efb.png)

**Comment by MusikAnimal** [comment]
Done, but I'm doing that same "lego" message thing that I'm told is discouraged, where the "most viewed pages" message is shared. Going to sidestep that issue for now, since I'm doing the same thing in many other places so will try fix all of them in one go. Thanks for the report!
