### ISSUE TITLE
Apache do not execute PHP code?

### ISSUE THREAD

**Issue by tarvos21** [MusikAnimal/pageviews#188]
Hi, I have tried to set up the app on my Macbook and AWS Linux server, but I encounter a problem with PHP code, maybe just for newbies, I am quite new to PHP app.

When I try to run the code with `php -S 0.0.0.0:8000`, the webpages show up correctly(mainly), but when I set up Apache2 and PHP5.6 server, there is nothing when I go to the `index.php`, there is only the first two line of copyright information in HTML code. So all PHP code are not executed in the `index.php` file.

What may be the problem? Apart from the `README.md` of the repo, any other resources for setting up the app on a Linux server?

**Comment by MusikAnimal** [comment]
The raw HTML code should at least show the nav, sidebar, etc., so indeed this sounds like a PHP issue and not JavaScript. It is very odd it somehow would render the footer but skip over all the other markup. Anything in the error log? It's probably at `/var/log/apache2/error.log`.

Have you been able to run other PHP apps? You might be missing some libraries... I use MacOS on my local and it ships with a lot of the PHP stuff. Meanwhile the production app is on a Linux box, but it is a shared environment and also already has everything installed. So I could easily be missing some steps in the README :-/

Also, did `composer install` throw any errors?

**Comment by tarvos21** [comment]
@MusikAnimal `composer install` goes great and I am able to run some simple PHP apps like classical `phpinfo();`. And sorry I do not make myself clear, the copyright information is not in the footer, it's in the Chrome console, the first two line of comments of the HTML:
```
<!-- Pageviews Analysis tool -->
<!-- Copyright 2016 MusikAnimal -->
<?php $currentApp = 'pageviews'; ?>
```
After the comment, the PHP is never executed. This is weird.

I checked Apache's error_log file, in it I find some errors like:
```
PHP message: PHP Fatal error:  Call to undefined function getallheaders() in /opt/bitnami/apps/myapp/htdocs/public_html/_head.php on line 35\n'
```
It seems like that the function `getallheaders()` in `_head.php` is not defined before called, what may be the cause of the problem?

Because I do not run it successfully with a LAMP stack on Ubuntu, so I choose to use the Bitnami package Linux AMI on AWS.

**Comment by tarvos21** [comment]
I will detect the problem further, thanks for your answer.
