### ISSUE TITLE
Add i18n translations

### ISSUE THREAD

**Issue by MusikAnimal** [MusikAnimal/pageviews#2]
Date formatting locale is in place, but it'd be nice if we could automatically translate the page. The app could accept a `lang=en-US` (for instance) to force a particular language, otherwise it will go off of JavaScript's `navigator.lang`

**Comment by kaldari** [comment]
See also https://phabricator.wikimedia.org/T127356

**Comment by kaldari** [comment]
This is pretty much finished in the https://github.com/MusikAnimal/pageviews/tree/php branch. Even the 3rd party components should now use localized messages. The remaining steps are:
* Add an interface in the Settings dialog to change your language (which should set a cookie).
* Register pageviews with TranslateWiki so we can start getting translations.

**Comment by MusikAnimal** [comment]
@kaldari 96 files changed at the time of writing! Quite an overhaul, to say the least :)

I think we can move forward with what we have now before adding a language selector.

First however I'd like to try to improve performance (page load, not AJAX). It seems [pageviews-test](http://tools.wmflabs.org/pageviews-test) is quite slow compared to [pageviews](http://tools.wmflabs.org/pageviews). The overhead of PHP will certainly take a bit of a toll, but I feel like it's going slower than it should be. Hopefully there's some caching mechanism through lighttpd that we could take advantage of. I would expect that if I reload the same page, with the same language cookie, it'd be quick to serve. Anything ideas?

**Comment by kaldari** [comment]
@MusikAnimal: PHP itself should not make much difference, maybe an extra 100ms. Loading all of Intuition may be what's slowing things down, but it will require some testing to figure out. If there were some way to cache the page, that would certainly help.

**Comment by kaldari** [comment]
It looks like loading and initializing Intuition is what is causing the extra slowness. Loading Intuition seems to add about 250-300ms, while initializing Intuition adds another 500ms or so. Add in the PHP overhead and it's almost an extra second.

**Comment by kaldari** [comment]
I think this is done now.
