### ISSUE TITLE
When a page is moved, the pageview tool doesn't report views of the page at the old location

### ISSUE THREAD

**Issue by mpeel** [MusikAnimal/pageviews#26]
Take as an example the English Wikipedia article on "First observation of gravitational waves". At present, the page view statistics link on the 'view history' page points to:
https://tools.wmflabs.org/pageviews/#start=2016-01-30&end=2016-02-18&project=en.wikipedia.org&platform=all-access&agent=user&pages=First_observation_of_gravitational_waves
The first view reported on this page was on the 14th February. However, the page has existed since 11 February at different locations, which are now redirects to the page listed at:
http://dispenser.homenet.org/~dispenser/cgi-bin/rdcheck.py?page=First_observation_of_gravitational_waves
e.g., the original name for the page was "Gravitational wave detection, February 2016", and page views from that page can still be found at:
https://tools.wmflabs.org/pageviews/#start=2016-01-30&end=2016-02-18&project=en.wikipedia.org&platform=all-access&agent=user&pages=Gravitational_wave_detection,_February_2016

Ideally, the tool would report the page view statistics for the page at *both* its current location and any previous locations. Would this be possible, please?

**Comment by MusikAnimal** [comment]
Yes, this particular scenario can be resolved with #9, which I hope to implement soon. In most cases it won't be a big deal, but there are performance issues I'll need to sort out for articles with lots of redirects, like [Google](http://dispenser.homenet.org/~dispenser/cgi-bin/rdcheck.py?page=Google). For this reason including redirects as a single statistic will be optional, defaulted-off.

This still isn't fool-proof for page moves, as one could move the page, then a new article created at the old location. There is #16 where we'd allow entering a page ID, which stays intact with page moves, however the Pageviews API goes by page name – so we end up with the same issue.

The only real solution is to recursively check a given page's move log, collect page view data on each such that we end up with accurate data for the full date range. This is not easy to do... and could be very expensive in terms of performance.

**Comment by kaldari** [comment]
I think #9 is the only realistic solution to this issue. I would suggest marking this as a duplicate.

**Comment by MusikAnimal** [comment]
@kaldari You don't think checking the move log would be worthwhile? That's one API call, followed by N more for each entry in the move log that falls within our date range. It shouldn't be too expensive, and I think will offer more accurate representation of what the user probably wants than including data on the redirects. For instance, an old location may have become a different article entirely, and never became a redirect to the new location.

Of course, it is still a lot of work! I say let's wait for T121912 to be resolved and go from there.

**Comment by MusikAnimal** [comment]
Upon further consideration, I'm not sure it's worth the effort to recursively query the move log of each page, given the pageviews API will hopefully resolve redirects on its own, see [T121912](https://phabricator.wikimedia.org/T121912). Closing as wontfix

**Comment by MusikAnimal** [comment]
Reopening. We've had some more complaints of this issue, and I think with some effort we can come up with a solid solution.

**Comment by MusikAnimal** [comment]
Issue migrated to Phabricator, please follow it for updates https://phabricator.wikimedia.org/T141332
