### ISSUE TITLE
Inaccurate data on pages titles with special characters

### ISSUE THREAD

**Issue by inter10** [MusikAnimal/pageviews#29]
Hi. I observed stats and in my opinion is somthing wrong. Stats of some pages are seems like too low, others are corect and like usually. Look at stats Wodzisław Śląski, Racibórz, Jastrzębie Zdrój or Wikipedia:Strona Główna in PL Wiki. Its dramatic low, in my opinion is not possible that only few people watching this page and its seems like somthing is wrong and stats not show all users... greetings  Swd polish wiki redactor.

**Comment by MusikAnimal** [comment]
@inter10 pl.wikipedia.org? I tried [Racibórz](http://tools.wmflabs.org/pageviews/#start=2016-02-05&end=2016-02-24&project=pl.wikipedia.org&platform=all-access&agent=user&pages=Racibórz) and got around 200 views a day. Make sure you have the "Platform" set to "All" and the "Agent" set to "User".

The data comes from the Wikimedia Foundation Pageviews API. I'm told what they give us is about 99.9999% accurate.

**Comment by inter10** [comment]
Look here: https://tools.wmflabs.org/pageviews/#start=2016-01-27&end=2016-02-26&project=pl.wikipedia.org&platform=all-access&agent=all-agents&pages=Województwo_śląskie   Only 64 view for Silesian Voivodeship it's not possible - unrealistic.  Since 23 and 24 febuary is somthing wrong. Stats get very low, seems like 10-20% real views. If im right it trobles only with articles with polish special letters like: "ł", "ó", "ę", "ą". Look Wrocław, Racibórz, Jastrzębie, Wodzisław Śląski, Województwo śląskie; all them since 23 and 24 febuary get so low views, too low unrealistic, I'm sure it.

**Comment by MusikAnimal** [comment]
Yes, I've received another report of this. Looks like something's up on the WMF-side. I'll get in touch with the analytics team. Thanks

**Comment by MusikAnimal** [comment]
See https://phabricator.wikimedia.org/T128295

**Comment by MusikAnimal** [comment]
The analytics team has successfully backfilled all the data. Closing
