### ISSUE TITLE
Linking to "lastest N days" or "last month"

### ISSUE THREAD

**Issue by MusikAnimal** [MusikAnimal/pageviews#36]
We need to allow for URL parameters to show just the latest data, or special ranges like "last month". Currently you'd have to manually remove the start/end parameters in order to show the most recent data. This makes it difficult to bookmark for those not in the know.

We could instead have:
* `start=latest-20&end=latest` which indicates the last 20 days
* `range=last-month` which will show the last month's data, and would have to ignore any `start` and `end` parameters if they were also passed in

I have a new branch that adds "last month", "last week" and "this week" buttons into the daterangepicker. I'd like to add the new URL logic to the same branch.

@kaldari thoughts on the URL params approach? Instead of `range` we could also do `start=last-month&end=last-month` or something, and have it auto-resolve to show the full month. That doesn't seem as clean, though.

**Comment by MusikAnimal** [comment]
See #38

**Comment by kaldari** [comment]
This looks pretty great. Couldn't find any problems with it.

**Comment by MusikAnimal** [comment]
Done
