### ISSUE TITLE
Add ability to import a list of pages to analyze

### ISSUE THREAD

**Issue by MusikAnimal** [MusikAnimal/pageviews#4]
Per request at https://meta.wikimedia.org/wiki/Talk:Community_Tech/Pageview_stats_tool

We'd like to be able to import a list of pages to check. This can be done via
* A `<textarea>` where we you can paste in a list of pages, either the URLs or page names
* [PagePile](http://tools.wmflabs.org/pagepile/)
* Category

When there are greater than 10 articles, combine view counts to form a single line chart rather than _N_ lines, which could look very clunky. A "reveal data" link could show a table view of the data, on a per-article per-day basis.

Initially this will only support articles within the same project.

**Comment by MusikAnimal** [comment]
Note I have a good start on this, but keep getting side-tracked. The code is in a different branch that I push to the repo.

**Comment by MusikAnimal** [comment]
Updates for anyone reading... we're going to need some major interface changes for this to be worthwhile. Importing a PagePile with 10 or less pages isn't really that helpful. I want to come up with a "mass query view", where we wouldn't show day-to-day stats, rather totals within the daterange for each given page. We could then import say, up to 500 pages, throttling API requests as necessary. We might also have to limit the daterange to just a few months time.

**Comment by MusikAnimal** [comment]
Pages could also be imported via WikiProject, going by the categorymembers API endpoint.

**Comment by MusikAnimal** [comment]
<script>alert('yeah')</script>

**Comment by kaldari** [comment]
FYI, this is being worked on in the pagepile branch (https://github.com/MusikAnimal/pageviews/commits/pagepile).
@MusikAnimal: It looks like if you send the pagepile API an invalid pagepile ID it totally explodes: https://tools.wmflabs.org/pagepile/api.php?id=12345&action=get_data&format=json&metadata=1&callback=jQuery21406094516076680612_1463091842373&_=1463091842374
I guess we'll need to check for this on our end.

**Comment by MusikAnimal** [comment]
Yup! Right now the code just assumes a bad response from Page Pile means no data, which playing around with the API is a safe assumption.

Categories are also now supported, just want to add the textarea and possibly also a way to list pages on a wiki page. For the latter I imagine we'll just parse the wikitext for `^[#\*]\s*\[\[(.*)\]\]\s*$` which will give us any pages in a bulleted or numbered list. We had one request for this feature from someone who works in outreach, so worth considering.

**Comment by MusikAnimal** [comment]
See also #111, going to add support to import Quarry datasets, and also template transclusions

**Comment by MusikAnimal** [comment]
Closing this in favour of #111
