### ISSUE TITLE
Error in javascript breaks pageviews page for russian locale

### ISSUE THREAD

**Issue by redreev** [MusikAnimal/pageviews#41]
Opened https://tools.wmflabs.org/pageviews/ for russian locale, found chart is not displayed.

Errors in the Google Chrome console: 
> tools.wmflabs.org/:27 Uncaught SyntaxError: Unexpected string
> application.js:12 Uncaught ReferenceError: i18nMessages is not defined

Indeed page contains incorrect javascripts: there's unescaped double quotes in the paramError3 string
``
<script type="text/javascript">
//<![CDATA[
   var i18nMessages = {
...
     paramError3: "Недопустимое значение <code>range</code>, вместо него будет использовано значение диапазона по умолчанию. См. <a href="/pageviews/url_structure">документацию</a> для получения дополнительной информации.",
``

**Comment by MusikAnimal** [comment]
@redreev Doh!!! I've deployed a fix. Sorry for the disruption and thank you for the report!

**Comment by redreev** [comment]
@MusikAnimal Thanks!
