### ISSUE TITLE
Upgrade to Chart.js 2.0

### ISSUE THREAD

**Issue by MusikAnimal** [MusikAnimal/pageviews#42]
This will by itself fix #35 and [T129197](https://phabricator.wikimedia.org/T129197), while also offering a bunch of new exciting features.

The release is still in beta, but might work for us. Docs are at http://nnnick.github.io/Chart.js/docs-v2

**Comment by MusikAnimal** [comment]
This is on hold for now until there is a stable release.

**Comment by MusikAnimal** [comment]
2.0.2 stable is out! This is still an enormous amount of work given the complete rewrite of the library, but I hope to get a start on this within the next few weeks.

**Comment by MusikAnimal** [comment]
Unfortunately still a few blockers, writing here for reference:
https://github.com/chartjs/Chart.js/issues/2056
https://github.com/chartjs/Chart.js/issues/2354
https://github.com/chartjs/Chart.js/issues/1980

**Comment by MusikAnimal** [comment]
@siteswapper @APerson241 @nemobis Perhaps you all would be interested in testing the new version of Pageviews, which includes a logarithmic scale option?

This is a major change to the tool, so there's probably bugs I haven't discovered yet. You can try it out here: https://tools.wmflabs.org/pageviews-test

The logarithmic scale option sometimes breaks the chart. Fortunately from my testing it seems this doesn't happen often, so I think it's OK to move forward with it. @siteswapper, your example (Donald Trump, Super Tuesday, Hillary Clinton) seems to work quite well ([link](http://localhost/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&start=2016-02-20&end=2016-03-10&pages=Donald_Trump|Super_Tuesday|Hillary_Clinton)), but @nemobis yours does not ([link](https://tools.wmflabs.org/pageviews-test/?project=it.wikipedia.org&platform=all-access&agent=user&start=2016-05-01&end=2016-05-30&pages=Salvatore_Aranzulla)) :(

For referencing purposes, I'm listing out the known issues. If you discover more I will add them accordingly.

**Known issues**:
* The tooltips (hovering over data points) for the radar chart are out of whack. Sometimes it shows multiple values and it's unclear which one it's referring to.
* The logarithmic option sometimes flakes out, for instance [here](https://tools.wmflabs.org/pageviews-test/?project=it.wikipedia.org&platform=all-access&agent=user&start=2016-05-01&end=2016-05-30&pages=Salvatore_Aranzulla).

Thank you for your help!

**Comment by nemobis** [comment]
MusikAnimal, 19/06/2016 21:09:
> but @nemobis <https://github.com/nemobis> yours does not (link
> <https://tools.wmflabs.org/pageviews-test/?project=it.wikipedia.org&platform=all-access&agent=user&start=2016-05-01&end=2016-05-30&pages=Salvatore_Aranzulla>)

The most obvious reason may be that "0" can't be represented in log 
scale. If the library doesn't replace the zeros with something else, you 
may have to.

**Comment by MusikAnimal** [comment]
@nemobis Good catch! I tried it, replacing the `0`'s with `1`'s, and I see a beautiful chart. However this is far from ideal because 1 pageview, as small as it may be, is still inaccurate. Is that just the way log scales work (zero can't possibly be displayed)? Using `null` instead of `1` also shows a chart, but nothing is plotted where there should be zeros. I suppose between the two options we'd rather see no data than inaccurate data?

**Comment by nemobis** [comment]
MusikAnimal, 19/06/2016 21:23:
> I suppose between the two options we'd rather see no data than
> inaccurate data?

Perhaps you could replace the 0 with 0.01 instead, or something like that?

**Comment by MusikAnimal** [comment]
> Perhaps you could replace the 0 with 0.01 instead, or something like that?

I can play around with the options for the Y axis labels, because by default it's showing labels for 0.05, 0.1. 0.5, etc, which are not helpful here. I'll also have to make a hack for the tooltips to show 0 instead of 0.01, and for the export data option, etc. Thanks for your help!

@nemobis Not sure if you saw my message at https://github.com/MusikAnimal/pageviews/issues/35#issuecomment-227015007? Now that we've got the log scale functionality ironed out, we just need to automate when to use it. The Theil index stuff is very alien to me. I feel like I need to dig up my old college textbooks first :)

**Comment by APerson241** [comment]
Nice job! I was playing around with it a bit, and noticed that sometimes the y-axis labels aren't powers of 10 - for example, [Merrick Garland](https://tools.wmflabs.org/pageviews-test/?project=en.wikipedia.org&platform=all-access&agent=user&range=latest-90&pages=Merrick_Garland) has 20,000, 9,000, 7,000, 5,000, 3,000, 1,000, 800, 600, 400, and 200. Is there any way you can make it so that, say, it shows 1,000, 10,000, and 100,000?

**Comment by MusikAnimal** [comment]
@APerson241 Currently I'm just letting the Chart library do the labels for me, but there is a callback where I could control this. However it seems powers of 10 may not be particularly helpful, especially when the max value in your example is less than 20K? I wouldn't expect to see a label for 100,000 at all, and if we only had two other labels (1,000 and 10,000) it would be somewhat difficult to make out what the values are without hovering over the data points.

**Comment by nemobis** [comment]
MusikAnimal, 19/06/2016 22:20:
> @nemobis <https://github.com/nemobis> Not sure if you saw my message at
> #35 (comment)
> <https://github.com/MusikAnimal/pageviews/issues/35#issuecomment-227015007>?
> Now that we've got the log scale functionality ironed out, we just need
> to automate when to use it. The Theil index stuff is very alien to me. I
> feel like I need to dig up my old college textbooks first :)

Yes sorry, I was thinking of a way to simplify it. From some quick 
checks, I think we may want to use the log scale when the Theil index is 
above 0.50.

To calculate the index of an array of values $views it should be enough 
to do something like:

$avg = array_sum( $views ) / count( $views );
$theil = 0.0;
foreach ( $views as $v ) {
	$theil += $v * log ( $v / $avg );
}
$theil = $theil / array_sum($views);

**Comment by MusikAnimal** [comment]
@nemobis Thanks!! This seems to do the trick :) For _multiple_ datasets, I've (a) found the max value of all datasets (b) appended the max value to each individual dataset (c) if any of the individual datasets (with max value appended) meet Theil index of 0.5 or larger, the log scale is used. Does that sound like a reasonable solution? Try it out [here](https://tools.wmflabs.org/pageviews-test/?project=it.wikipedia.org&platform=all-access&agent=user&start=2016-05-01&end=2016-05-30&pages=Salvatore_Aranzulla|Google) and [here](https://tools.wmflabs.org/pageviews-test/?project=en.wikipedia.org&platform=all-access&agent=user&start=2016-02-20&end=2016-03-10&pages=Donald_Trump|Super_Tuesday|Hillary_Clinton).

If you check/uncheck the log scale checkbox, you enter "manual mode", and from there the tool does not attempt to automatically use the log scale until you refresh the page again.

**Comment by nemobis** [comment]
The vertical axis looks slightly weird:
![pageviews-log](https://cloud.githubusercontent.com/assets/901528/16213072/f0aea964-374c-11e6-8180-7a2c86d5634e.png)

But the detection of the cases when to use log scale seems to work quite well! Well done.

**Comment by MusikAnimal** [comment]
> The vertical axis looks slightly weird:

I'll create a separate issue for this. Implementing a fool-proof solution might be a little tricky, and in most cases the labels don't overlap as they do here.

**Comment by MusikAnimal** [comment]
3-month long issue resolved and DEPLOYED! 😄  Thanks again @nemobis and @APerson241 for your help!
