### ISSUE TITLE
"Not seeing the chart?" message is incomplete

### ISSUE THREAD

**Issue by John-of-Reading** [MusikAnimal/pageviews#48]
The message "Not seeing the chart..." mentions ad blockers but fails to mention that the browser must be set to allow cookies from https://tools.wmflabs.org

My browser is configured with a very tight cookie policy. I found that I had to add an exception for tools.wmflabs.org even though the tool does not create a cookie.

**Comment by MusikAnimal** [comment]
Actually it does set cookies for the translation tool to work, that includes English. I was not aware this was required, however. I'll update the notice accordingly, thanks!

**Comment by MusikAnimal** [comment]
See #52. We actually don't need cookies at all for the tool to work, just need to not set the language cookie if cookies are disabled. Working a fix. Closing this as invalid since it's actually a bug
