### ISSUE TITLE
Remove cookie-dependency

### ISSUE THREAD

**Issue by foobar13373** [MusikAnimal/pageviews#52]
Instead of simply forcing the user to enable cookies (no, I won't!), you should modify the code in a way that it works without cookies. Why would a website that shows a plain diagramm and has no user-context or login-context need cookies? Rather suspicous.

**Comment by MusikAnimal** [comment]
It's related to the [Intuition framework](https://github.com/Krinkle/intuition), but I think I know what's going on. Will work on a fix. Thanks

**Comment by kaldari** [comment]
@foobar13373: It uses cookies so that you don't have to set your language each time you visit. I suppose if your language is English, we could skip setting the cookie though. What's your idea @MusikAnimal?

**Comment by kaldari** [comment]
Is there a way to detect that cookies are disabled?

**Comment by MusikAnimal** [comment]
@kaldari More at [T131167](https://phabricator.wikimedia.org/T131167). Intuition still works with cookies disabled, correctly translating based on the language specified in the request header. Only somewhere down the chain it's writing to a cookie when it doesn't have to. Not sure how XTools and others do it, but we should adopt this. I tried commenting out code to figure what's making it break. It's not our JS, and not those initial lines in `_head.haml`. Obviously we have register our domain with Intuition or else it won't translate. If you're able to take a look that'd be great, I'm stumped.

**Comment by kaldari** [comment]
It looks like this is actually failing due to trying to access LocalStorage. Should be easy enough to fix.

**Comment by MusikAnimal** [comment]
Should be all set. Some functionality may be lost as result of cookies being disabled, however. Thanks again to Kaldari for fixing this!
