### ISSUE TITLE
Doesn't work for projects that begin with www, like www.mediawiki.org

### ISSUE THREAD

**Issue by kaldari** [MusikAnimal/pageviews#55]
This is because the pageview API expects these to have the www chopped off:
https://wikimedia.org/api/rest_v1/metrics/pageviews/per-article/mediawiki/all-access/all-agents/Help%3AVisualEditor%2FUser_guide/daily/2016030100/2016033100

**Comment by kaldari** [comment]
Should be fixed by above commit.

**Comment by MusikAnimal** [comment]
Weird, I fixed this then I guess broke it again. Thanks!

**Comment by MusikAnimal** [comment]
@kaldari Although I think maybe we should update [site_map.js](https://github.com/MusikAnimal/pageviews/blob/master/javascripts/shared/site_map.js#L842) to specify `mediawiki.org` (without www) as the valid project name, like we do with `wikidata.org`. That would make the validations match what the API wants.

It'd still be good to allow `www`, as it's reasonable to assume that is valid. So we could add your code to [validateProject()](https://github.com/MusikAnimal/pageviews/blob/master/javascripts/pageviews.js#L891), stripping out the `www` of `$(config.projectInput)`, and re-set the value of that input. How does that sound?

**Comment by kaldari** [comment]
@MusikAnimal: Sounds good to me. I probably won't have any more time this evening to work on it, but if you want to you're welcome to go head.

**Comment by MusikAnimal** [comment]
Done! Thanks again

**Comment by MusikAnimal** [comment]
@kaldari One last thing... unfortunately Babel only converts syntax, not functionality. I guess `String.startsWith` broke IE and Safari 8, as caught by the acceptance tests. I just added a polyfill and all is well. The polyfills for most of these simple functions can be found on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#Polyfill).

Barring something really straightforward, I've gotten in the habit of making a pull request to see if the tests pass. You can run the Firefox tests locally very easily, but there's a lot of setup to get Selenium working on Safari/IE, so I just let Travis do it.

**Comment by kaldari** [comment]
@MusikAnimal: Yeah, I was wondering about that. I thought that Babel would add a polyfill for it, but I guess it's not that smart :) Good idea about doing pull requests for testing. I'll do that next time.
