### ISSUE TITLE
Support for outreachwiki

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MusikAnimal/pageviews#57]
I tried to get pageviews to work for outreachwiki, but queries like
https://tools.wmflabs.org/pageviews/#project=outreach.wikimedia.org&platform=all-access&agent=user&range=latest-20&pages=GLAM
result in "No data found for the page [GLAM](https://outreach.wikimedia.org/wiki/GLAM)".

**Comment by MusikAnimal** [comment]
It looks like the RESTBase API hasn't added outreach.wikimedia.org yet :-/

I guess I will have to remove it from Pageviews Analysis site map, and if typed in, show the error `outreach.wikimedia.org is not a valid project, or is not currently supported by the Wikimedia API` as currently it would just say `is not a valid project`, when it obviously is valid.

I can open a phab report in hopes they will add support for Outreach, but in the meantime there's nothing I can do. Sorry!

**Comment by Daniel-Mietchen** [comment]
Yes, please report it on Phabricator.

**Comment by MusikAnimal** [comment]
@Daniel-Mietchen [https://phabricator.wikimedia.org/T132313](T132313)

**Comment by MusikAnimal** [comment]
Phab is now at https://phabricator.wikimedia.org/T130249

**Comment by MusikAnimal** [comment]
@Daniel-Mietchen Resolved! Data is now being populated for Outreach Wiki http://tools.wmflabs.org/pageviews/?project=outreach.wikimedia.org&platform=all-access&agent=user&range=latest-20&pages=Main_Page
