### ISSUE TITLE
Calculation errors

### ISSUE THREAD

**Issue by Daniel-Mietchen** [MusikAnimal/pageviews#58]
The relative order of totals and averages in
https://tools.wmflabs.org/pageviews/#project=en.wikipedia.org&platform=all-access&agent=user&start=2016-03-06&end=2016-04-05&pages=Cat|Dog|Lion|Cheetah|Rabbit|Anaconda|Dinosaur|Animal
does not make sense. For instance, "Dinosaur" always has more daily page views than "Cheetah" during this period, but the reported totals and averages are higher for Cheetah than for Dinosaur.

**Comment by Daniel-Mietchen** [comment]
When clicking on the link in the comment above, the reported totals and averages I get seem to be correct:
1.444.122 (46.585/day) Cat 262.064 (8.454/day) Dog 275.652 (8.892/day) Lion 210.372 (6.786/day) Cheetah 120.136 (3.875/day) Rabbit 131.086 (4.229/day) Anaconda 82.695 (2.668/day) Dinosaur 187.277 (6.041/day) Animal 174.840 (5.640/day).

In the other tab that prompted me to report the issue, the respective numbers are:
1.444.122 (46.585/day) Cat 187.277 (6.041/day) Dog 131.086 (4.229/day) Lion 120.136 (3.875/day) Cheetah 262.064 (8.454/day) Rabbit 210.372 (6.786/day) Anaconda 174.840 (5.640/day) Dinosaur 82.695 (2.668/day) Animal 275.652 (8.892/day)

In that original tab, I had played around with a number of different article titles and hit the 10-item limit a number of times, so I guess that the calculation error may have something to do with the reorganization after deleting or perhaps adding an item.

**Comment by MusikAnimal** [comment]
I think I fixed something else than broke this. I will get a fix out ASAP! Thank you

**Comment by MusikAnimal** [comment]
@Daniel-Mietchen Should be fixed now. Thank you again for identifying and reporting this critical bug! Surprised this hasn't come up yet.
