### ISSUE TITLE
Allow color changes

### ISSUE THREAD

**Issue by alchimista** [MusikAnimal/pageviews#6]
When colors are very similar, it gets hard to understand the chart, an option to choose colors would be nice. Example:
https://tools.wmflabs.org/pageviews/#start=2015-11-12&end=2016-02-09&project=pt.wikipedia.org&platform=desktop&agent=user&pages=Futebol_Clube_do_Porto|Sporting_Clube_de_Portugal|Sport_Lisboa_e_Benfica

**Comment by MusikAnimal** [comment]
Add options to choose a palette would be nice, the only issue for me anyway is I don't know what palettes to use =P The first five colours are what was given with the original API demo. The last 5 (so when you have 10 articles) are colours I chose using https://coolors.co/ Other palette engines have similar issues. Just need to find one that is designed for charts, and allows up to 10 colours.

**Comment by kaldari** [comment]
I think just picking a better set of colors would be much better than adding an interface for setting the colors manually. Here is a good sequence of 10 colors from ColorBrewer (which is specifically designed for data visualization):
#a6cee3
#b2df8a
#fb9a99
#fdbf6f
#cab2d6
#1f77b4
#33a02c
#e31a1c
#ff7f00
#6a3d9a

**Comment by MusikAnimal** [comment]
Thanks! Just the tool I was looking for :) Let's come up with a few options if we think that's a good idea. Otherwise we can go with a single palette that serves as sort of a happy medium.

**Comment by kaldari** [comment]
Also, we'll probably need to invert the text color for some of these (so that the text is more readable when on top of the color).

**Comment by MusikAnimal** [comment]
True, unfortunately not easy to do (I think). I've got a new branch I'm close to being ready to deploy that adds color options https://github.com/MusikAnimal/pageviews/pull/23. I guess let's create a new issue for inverting the text color.

**Comment by MusikAnimal** [comment]
Done with #23
