### ISSUE TITLE
Support Outreach Wiki

### ISSUE THREAD

**Issue by Sadads** [MusikAnimal/pageviews#67]
Hey, I am an admin over on outreach.wikimedia.org and it still has stats.grok.se in the history header. I tried to run the data for outreach, but it was coming back with "no data" --- is this a data problem or an interface problem?

**Comment by Sadads** [comment]
Nevermind, the outstanding concern is at https://phabricator.wikimedia.org/T130249

**Comment by MusikAnimal** [comment]
Yes also at [T132313](https://phabricator.wikimedia.org/T132313) and https://github.com/MusikAnimal/pageviews/issues/57 Sorry I can't do anything!
