### ISSUE TITLE
Javascript error when using as search engine with terms with spaces

### ISSUE THREAD

**Issue by Thue** [MusikAnimal/pageviews#71]
I am using Wikipedia article statistics as a Chromium search engine (background reading: http://www.tekrevue.com/tip/chrome-custom-search-engine/ ).

Specifically, I created the search engine with the following string: 

https://tools.wmflabs.org/pageviews/#project=en.wikipedia.org&platform=all-access&agent=user&pages=%s

Where Chromium will replace %s with the term I searched for, when used.

However, this fails (no chart is shown) when searching for terms with spaces in them, for example "HTML5 audio", with the following javascript error in the console: application.js:9 "Uncaught TypeError: Cannot read property 'label' of undefined." The chart then fails to appear. Bizarrely, hitting enter in the browser address line without any changes seems to cause the chart to display correctly.

When using Wikipedia article statistics normally (ie not as a search engine), the search terms embedded in the URL actually have their spaces replaced by underscores. So this error is somewhat the result of irregular use. But it would still be nice if it worked.

**Comment by MusikAnimal** [comment]
Should be fixed now. Thanks for the report!
