### ISSUE TITLE
Can't change dates 1 year back

### ISSUE THREAD

**Issue by Smallbones** [MusikAnimal/pageviews#8]
I try to change the dates, e.g. so I can see the same month 1 year back, 2 yeaars back, etc. and it doesn't work

**Comment by MusikAnimal** [comment]
Data from the new pageviews API does not go back earlier than October 2015. Sorry.

**Comment by MusikAnimal** [comment]
However I will try to add some sort of notice about this so people don't get confused.

**Comment by tbertels** [comment]
Why not convert the old data?

**Comment by MusikAnimal** [comment]
Quite simply, it is inaccurate. Additionally this is really on the WMF-side... I'd have to do some crazy mapping of the data to a localized database in order to accomplish this myself.

**Comment by nemobis** [comment]
> There are plans to backfill older data, but the Analytics team doesn't know when that might happen yet.

https://wikitech.wikimedia.org/wiki/Analytics/PageviewAPI#Updates_and_backfilling

**Comment by MusikAnimal** [comment]
Good to know, will adjust permitted date range when we know older data is reliable.

**Comment by tbertels** [comment]
Thanks for the info, that's great news!
