### ISSUE TITLE
Pageviews Analysis – FAQ not translatable

### ISSUE THREAD

**Issue by ANDR0BETA** [MusikAnimal/pageviews#80]
The "Pageviews Analysis – FAQ" is not currently listed in translatewiki.net, could we have that done please? Also the URL structure, but that is less important.

Thank you :)

**Comment by MusikAnimal** [comment]
Sure! It's a lot of stuff, just never got around to adding it. There's also another FAQ for Topviews and Langviews, but some of the messages will be shared. This is still pretty easy to do, so should have it out before too long. Thanks!

**Comment by MusikAnimal** [comment]
FAQ and URL structure pages have full i18n support now :) Thanks again
