### ISSUE TITLE
Date bug on zhwiki

### ISSUE THREAD

**Issue by Peace1-zhwiki** [MusikAnimal/pageviews#82]
Hi, this problem has existed since 2016/04/01. The date would show wrong value (such as 3/0) when using this tool on zhwiki. (For example, [this page](https://tools.wmflabs.org/pageviews/#project=zh.wikipedia.org&platform=all-access&agent=user&range=latest-90&pages=荒勝文策)). And the date also shows wrong if you choose specific date (you can try yourself at "日期範圍"). Can someone fix it? Thanks!

**Comment by Peace1-zhwiki** [comment]
The screenshot is like this: http://ppt.cc/yIuT1

**Comment by MusikAnimal** [comment]
@Peace1-zhwiki This should be fixed now with https://github.com/MusikAnimal/pageviews/commit/a867da76ef4410c89abe31a040678df2830b9a85, please confirm! Apologies for the bug

**Comment by Peace1-zhwiki** [comment]
Thanks! It works well now.

**Comment by MusikAnimal** [comment]
Excellent. Thank you for the report!
