### ISSUE TITLE
Can't use magic words on some i18n messages

### ISSUE THREAD

**Issue by stadtwald** [MusikAnimal/pageviews#85]
I recently contributed the Māori language translation to the pageviews tool.  Because definite articles in Māori are either plural or singular, I used the {{plural}} function to ensure that correct grammar was calculated for four of the messages.

However, this seems to be causing a crash in the server-side code, specifically:
    [MessagesFunctions::plural] Invalid number argument to {{PLURAL: ...}} in /data/project/pageviews/pageviews/vendor/krinkle/intuition/language/MessagesFunctions.php on line 123

I think the issue is occurring because the variable ($1) is being calculated client-side rather than server-side, so the server-side logic is seeing the variable token ("$1") rather than the number.

I have received this error at the pageviews installation at:
    https://tools.wmflabs.org/pageviews/

**Comment by stadtwald** [comment]
I should clarify that the crash is occurring after the Māori language is selected.

**Comment by MusikAnimal** [comment]
@stadtwald You are correct, for some messages the parameter is computed clientside, so with {{PLURAL}} you're trying to compute numerical operations on placeholder text when the page first loads. Sorry about that, I have manually removed breaking usage of magic words, and indicated where not to use the in `qqq.json`.

I hope to implement a workaround soon, see [T133766](https://phabricator.wikimedia.org/T133766)

In the meantime I guess I should manually review the messages before deploying.

Thanks!

**Comment by MusikAnimal** [comment]
@stadtwald Fixed and deployed! I've also restored your previously breaking i18n messages :)

Also, I noticed the messages for the days of the week (`su`, `mo`, `tu`, etc) are not abbreviated for Mãori. This causes the date selector to be oversized and hard to use. Try it out now to see what I mean.

Thank you for your invaluable assistance!!! Closing

**Comment by stadtwald** [comment]
Excellent, thanks for the patch @MusikAnimal.

As for the days of the week, I've abbreviated them now.
