### ISSUE TITLE
Update FAQ to explain issue with false positives

### ISSUE THREAD

**Issue by kipala** [MusikAnimal/pageviews#91]
First of thank you so much for this tool, it is great help for gauging our readers interest!  I linked it to the Front page of swwiki.

Using it I notice a strange thing. probably it is normal that certain lookup pages appear very high, that can be filtered out. BUT on swwiki there is users talk page which constantly shows up with large (by our standards) number of views. Majadiliano ya mtumiaji:Yusuph Pius. It is a user with little activity. he has a text on his user page, which however does not show up if I search the topic in swwiki or on google. Can that be a hitch?
Another strange thing is that when I look at 2016 January and February views there is a page "-" (title: just "dash") as the top viewed page but it does not exist (never existed), and does not return in March etc.

**Comment by MusikAnimal** [comment]
@kipala These are "false positives", and unfortunately are unavoidable. Most likely someone wrote an automated program to test or scrape those pages, so their "user agent" looks like a human but it isn't. Basically if you see something that doesn't look right, it probably isn't.

Try clicking on the numbers on the right side to open up a page in the Pageviews tool. You'll likely see that there was a spike on a certain day. Another strategy is to compare the view counts of mobile versus desktop. Most automated programs will show as desktop, and given how popular mobile is, if there are very few mobile views but a ton of desktop views, it's probably a false positive.

If you find a particular article that got a ton of views that seems like it's legitimate, but you're not really sure why it go so many views, you can contact the WMF Analytics team as they might be able to provide some answers.

I need to update the FAQ to explain all of this, so changing this issue to be that. Best

**Comment by MusikAnimal** [comment]
FAQ updated
